server {
    listen 80;
    server_name aitranslate.torayhk.com;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name aitranslate.torayhk.com;

    ssl_certificate /etc/letsencrypt/live/aitranslate.torayhk.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/aitranslate.torayhk.com/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    client_max_body_size 100M;

    proxy_connect_timeout 300s;
    proxy_send_timeout 300s;
    proxy_read_timeout 300s;
    send_timeout 300s;

    location /api/ {
        proxy_pass http://multilanguage_translator_be:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header X-Amzn-Oidc-Data        $http_x_amzn_oidc_data;
        proxy_set_header X-Amzn-Oidc-Identity    $http_x_amzn_oidc_identity;
        proxy_set_header X-Amzn-Oidc-Accesstoken $http_x_amzn_oidc_accesstoken;
        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;

        proxy_method $request_method;

        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;

        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain; charset=utf-8';
            add_header 'Content-Length' 0;
            return 204;
        }
    }

    location / {
        proxy_pass http://multilanguage_translator_fe:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 600s;
        proxy_send_timeout 600s;
        proxy_read_timeout 600s;
    }
}
