# Generated by Django 5.1.6 on 2025-08-25 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordsuggestion',
            name='frequency_percentage',
            field=models.FloatField(default=0.0, help_text='Tỷ lệ phần trăm xuất hiện'),
        ),
        migrations.AddField(
            model_name='keywordsuggestion',
            name='suggestion_count',
            field=models.IntegerField(default=1, help_text='Số lần từ này được đề xuất'),
        ),
        migrations.CreateModel(
            name='KeywordQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japanese', models.TextField(blank=True, null=True)),
                ('english', models.TextField(blank=True, null=True)),
                ('vietnamese', models.TextField(blank=True, null=True)),
                ('chinese_traditional', models.TextField(blank=True, null=True)),
                ('chinese_simplified', models.TextField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
