# Generated by Django 5.2.1 on 2025-08-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_keywordsuggestion_frequency_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="auth_provider",
            field=models.CharField(
                choices=[("local", "Local"), ("cognito", "Cognito")],
                default="local",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="cognito_sub",
            field=models.CharField(
                blank=True,
                help_text="Cognito User Pool Subject ID",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
