# Generated by Django 5.2.1 on 2025-11-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_keywordsuggestion_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
