# Generated by Django 5.1.6 on 2025-11-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_customuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordqueue',
            name='bengali',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywordqueue',
            name='hindi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywordqueue',
            name='indonesian',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywordqueue',
            name='oriya',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywordqueue',
            name='thai',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywordsuggestion',
            name='bengali',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywordsuggestion',
            name='hindi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywordsuggestion',
            name='indonesian',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywordsuggestion',
            name='oriya',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywordsuggestion',
            name='thai',
            field=models.TextField(blank=True, null=True),
        ),
    ]
