# Generated by Django 5.1.6 on 2026-03-06 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_customuser_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japanese', models.TextField(blank=True, null=True)),
                ('english', models.TextField(blank=True, null=True)),
                ('vietnamese', models.TextField(blank=True, null=True)),
                ('chinese_traditional', models.TextField(blank=True, null=True)),
                ('chinese_simplified', models.TextField(blank=True, null=True)),
                ('thai', models.TextField(blank=True, null=True)),
                ('bengali', models.TextField(blank=True, null=True)),
                ('hindi', models.TextField(blank=True, null=True)),
                ('indonesian', models.TextField(blank=True, null=True)),
                ('oriya', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, help_text='Ghi chú cá nhân', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_keywords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
