# Generated by Django 5.1.6 on 2026-03-06 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_private_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatekeyword',
            name='suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_keywords', to='api.keywordsuggestion'),
        ),
    ]
