# Generated by Django 6.0 on 2026-05-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_add_indexes_keyword_status_is_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryqueuesettings',
            name='min_suggesters_for_queue',
            field=models.PositiveIntegerField(default=2, help_text='Tối thiểu số người đề xuất khác nhau (cùng một cặp ngôn ngữ) để từ vào hàng chờ'),
        ),
    ]
