# Generated by Django 6.0 on 2026-06-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_unused_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordsuggestion',
            name='frequency_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='keywordsuggestion',
            name='suggestion_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='libraryqueuesettings',
            name='min_suggesters_for_queue',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='privatekeyword',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
