# Generated by Django 6.0 on 2026-07-09 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_remove_language_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywordsuggestion',
            name='suggestion_count',
        ),
        migrations.DeleteModel(
            name='KeywordQueue',
        ),
    ]
