# Generated by Django 6.0 on 2026-07-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_remove_keywordsuggestion_suggestion_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatekeyword',
            name='note',
        ),
    ]
