# Generated by Django 6.0 on 2026-07-09 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_remove_privatekeyword_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywordsuggestion',
            name='frequency_percentage',
        ),
    ]
