# Generated by Django 6.0 on 2026-07-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_remove_keywordsuggestion_frequency_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatedfile',
            name='folder_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
